-- Lab 06 — Internals
-- Run: i /repo/labs/07-internals.sql
-- Bloat experiment runs on a copy without indexes (orders_bloat) → orders is untouched
-- (updating orders itself after the lab 05 indexes took ~6 min on Docker Desktop)
\timing on

\echo '== 1. Pages & tuples =='
SELECT current_setting('block_size') AS block_size;
SELECT relpages, reltuples::bigint, round(reltuples / relpages) AS rows_per_page
FROM pg_class WHERE relname = 'orders';
SELECT ctid, id FROM orders LIMIT 3;

\echo '== 2. Sizes =='
SELECT pg_size_pretty(pg_relation_size('orders'))       AS heap,
       pg_size_pretty(pg_indexes_size('orders'))        AS indexes,
       pg_size_pretty(pg_total_relation_size('orders')) AS total;

\echo '== 3. WAL generated by 10K updates =='
SELECT pg_current_wal_lsn() AS before \gset
UPDATE orders SET qty = qty WHERE id <= 10000;
SELECT pg_size_pretty(pg_wal_lsn_diff(pg_current_wal_lsn(), :'before')) AS wal_generated;

\echo '== 4. Bloat experiment (copy table) =='
DROP TABLE IF EXISTS orders_bloat;
CREATE TABLE orders_bloat AS SELECT * FROM orders;
SELECT pg_size_pretty(pg_relation_size('orders_bloat')) AS before_update;      -- ~73 MB
UPDATE orders_bloat SET qty = qty;
SELECT pg_size_pretty(pg_relation_size('orders_bloat')) AS after_update;       -- ~147 MB
VACUUM orders_bloat;
SELECT pg_size_pretty(pg_relation_size('orders_bloat')) AS after_vacuum;       -- ~147 MB
VACUUM FULL orders_bloat;
SELECT pg_size_pretty(pg_relation_size('orders_bloat')) AS after_vacuum_full;  -- ~73 MB
DROP TABLE orders_bloat;

\echo '== 5. Planner stats =='
ANALYZE orders;
SELECT attname, n_distinct, most_common_vals
FROM pg_stats WHERE tablename = 'orders' AND attname IN ('status', 'qty');
EXPLAIN ANALYZE SELECT * FROM orders WHERE status = 'paid';

-- 🏋️ Exercises
-- a) DELETE 50% of a copy of orders and compare size before/after VACUUM
-- b) Change random_page_cost (SET) and see if the plan changes
